//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyHealthCareDataStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class empanelment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empanelment()
        {
            this.hosp_emp_emergency_map = new HashSet<hosp_emp_emergency_map>();
        }

        [DisplayName("Empanelment Id")]
        public int empanelment_id { get; set; }

        [DisplayName("Empanelment Type")]
        public string empanelment_type { get; set; }

        [DisplayName("Empanelment Code")]
        public string empanelment_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hosp_emp_emergency_map> hosp_emp_emergency_map { get; set; }
    }
}
