//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyHealthCareDataStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class hosp_emp_emergency_map
    {
        public int hosp_emp_emergency_map1 { get; set; }

        [DisplayName("Empanelment ID")]
        public Nullable<int> empanelment_id { get; set; }

        [DisplayName("Hospital ID")]
        public Nullable<int> hospital_id { get; set; }

        [DisplayName("Emergency Number")]
        public string emergency_num { get; set; }
    
        public virtual empanelment empanelment { get; set; }
        public virtual hospital_medibuddy hospital_medibuddy { get; set; }
    }
}
