//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyHealthCareDataStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_cost_manual
    {
        public int medical_cost_id { get; set; }
        public Nullable<int> hospital_id { get; set; }
        public Nullable<int> medical_service_id { get; set; }
        public Nullable<double> medical_cost { get; set; }
    
        public virtual hospital_manual hospital_manual { get; set; }
        public virtual medical_services medical_services { get; set; }
    }
}
