//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyHealthCareDataStore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class medical_services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medical_services()
        {
            this.medical_cost_manual = new HashSet<medical_cost_manual>();
            this.medical_cost_medibuddy = new HashSet<medical_cost_medibuddy>();
        }

        [DisplayName("Medical Service ID")]
        public int medical_service_id { get; set; }

        [DisplayName("Medical Service Name")]
        public string medical_service_name { get; set; }

        [DisplayName("Medical Service Category")]
        public string medical_service_category { get; set; }

        [DisplayName("Medical Service Description")]
        public string medical_service_description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medical_cost_manual> medical_cost_manual { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medical_cost_medibuddy> medical_cost_medibuddy { get; set; }
    }
}
