//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyHealthCareDataStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyHealthCareEntities : DbContext
    {
        public EasyHealthCareEntities()
            : base("name=EasyHealthCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hospital_manual> hospital_manual { get; set; }
        public virtual DbSet<hospital_medibuddy> hospital_medibuddy { get; set; }
        public virtual DbSet<hospital_medibuddy_backup> hospital_medibuddy_backup { get; set; }
        public virtual DbSet<hospitalSpeciality> hospitalSpecialities { get; set; }
        public virtual DbSet<InsuranceCompany> InsuranceCompanies { get; set; }
        public virtual DbSet<medical_services> medical_services { get; set; }
        public virtual DbSet<AssociatedInsuranceCompany> AssociatedInsuranceCompanies { get; set; }
        public virtual DbSet<medical_cost_manual> medical_cost_manual { get; set; }
        public virtual DbSet<medical_cost_medibuddy> medical_cost_medibuddy { get; set; }
        public virtual DbSet<empanelment> empanelments { get; set; }
        public virtual DbSet<hosp_emp_emergency_map> hosp_emp_emergency_map { get; set; }
        public virtual DbSet<user_hospital> user_hospital { get; set; }
    }
}
